baseURL = 'https://open.devies.se'
languageCode = 'en-us'
title = "Devies' open source"
theme = 'hugo-nederburg-theme'

# Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "https://www.devies.se/contact/"
  weight = 3

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true

  [params.social]
  email         = "hello@devies.se"
  linkedin      = "https://www.linkedin.com/company/deviesdevelopment"
  instagram     = "https://www.instagram.com/deviesgbg/"
  github        = "https://www.github.com/deviesdevelopment/"

  # Add a writer, then use it in the markdown front matter like this: writer = "Lukas Herman"
  [params.writers]
    [params.writers."Peter Makra"]
    #link = "https://aswe.do"
    email = "peter.makra@devies.se"
    bio = [
      "Nothing special."
    ]
    
    linkedin      = "linkedin.com/in/petermakra"
    instagram     = "instagram.com/mcraa"
    github        = "github.com/mcraa"